[package]
name = "about-this-linux-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpuid = "0.1"
lxinfo = { git = "https://github.com/vars1ty/lxinfo.git" }
